//! Versioned REST payloads for opaque synchronization.

use heartlink_shared_models::{CipherRecord, RevisionedRecord};
use serde::{Deserialize, Serialize};
use uuid::Uuid;

/// Current HTTP wire protocol version.
pub const PROTOCOL_VERSION: u16 = 1;

/// Application-level authenticated handshake protocol version.
pub const HANDSHAKE_PROTOCOL_VERSION: u16 = 1;

/// Service health response.
#[derive(Debug, Serialize, Deserialize)]
pub struct HealthResponse {
    /// Stable status value.
    pub status: String,
    /// Protocol version understood by this service.
    pub protocol_version: u16,
}

/// Starts an ephemeral X25519 handshake with a signed server identity.
#[derive(Debug, Serialize, Deserialize)]
pub struct HandshakeRequest {
    /// Handshake wire version.
    pub protocol_version: u16,
    /// Service identity expected by the client (`cloud` or `update`).
    pub audience: String,
    /// Base64URL-encoded 32-byte X25519 public key.
    pub client_public_key: String,
    /// Base64URL-encoded random nonce generated by the client.
    pub client_nonce: String,
    /// Current Unix timestamp used to reject stale handshakes.
    pub client_time: i64,
}

/// Signed server half of the authenticated ephemeral handshake.
#[derive(Debug, Serialize, Deserialize)]
pub struct HandshakeResponse {
    /// Handshake wire version.
    pub protocol_version: u16,
    /// Service identity bound into the signature.
    pub audience: String,
    /// Long-term signing-key identifier.
    pub key_id: String,
    /// Short-lived request-signing session identifier.
    pub session_id: String,
    /// Base64URL-encoded server X25519 public key.
    pub server_public_key: String,
    /// Base64URL-encoded server nonce.
    pub server_nonce: String,
    /// Base64URL-encoded Ed25519 identity public key.
    pub identity_public_key: String,
    /// Unix timestamp when the request-signing session expires.
    pub expires_at: i64,
    /// Base64URL-encoded Ed25519 signature over the canonical transcript.
    pub signature: String,
}

/// Signed description of the latest application release.
#[derive(Debug, Serialize, Deserialize)]
pub struct UpdateManifestResponse {
    /// Stable update channel.
    pub channel: String,
    /// Target platform, for example `windows-x64`.
    pub platform: String,
    /// Semantic product version.
    pub version: String,
    /// Monotonically increasing application build number.
    pub build: u32,
    /// Oldest build allowed to continue without a mandatory update.
    pub minimum_supported_build: u32,
    /// Whether this release must be installed before cloud use continues.
    pub mandatory: bool,
    /// Human-readable release notes.
    pub notes: String,
    /// Unix timestamp when the release was published.
    pub published_at: i64,
    /// Exact archive size in bytes.
    pub size: u64,
    /// Uppercase hexadecimal SHA-256 of the archive.
    pub sha256: String,
    /// Same-origin path used to download the archive.
    pub download_path: String,
    /// Signed package type: `installer-exe` or `portable-zip`.
    #[serde(default)]
    pub package_format: String,
    /// Signing key identifier.
    pub key_id: String,
    /// Base64URL-encoded Ed25519 signature over the canonical manifest.
    pub signature: String,
}

/// Account registration/login input. This password is not the vault master password.
#[derive(Debug, Deserialize)]
pub struct CredentialsRequest {
    /// Account login identifier.
    pub email: String,
    /// International-format mobile number required when creating an account.
    #[serde(default)]
    pub phone: Option<String>,
    /// Service authentication password.
    pub password: String,
}

/// Recovery delivery channel selected by the account owner.
#[derive(Clone, Copy, Debug, Serialize, Deserialize, Eq, PartialEq)]
#[serde(rename_all = "snake_case")]
pub enum RecoveryChannel {
    /// Deliver through the registered email address.
    Email,
    /// Deliver through the registered mobile number.
    Phone,
}

/// Credential being recovered.
#[derive(Clone, Copy, Debug, Serialize, Deserialize, Eq, PartialEq)]
#[serde(rename_all = "snake_case")]
pub enum RecoveryPurpose {
    /// Cloud account login password.
    AccountPassword,
    /// HeartLink application unlock verifier.
    UnlockPassword,
}

/// Starts a privacy-preserving recovery challenge.
#[derive(Debug, Deserialize)]
pub struct RecoveryRequest {
    /// Registered email address or mobile number.
    pub identifier: String,
    /// Where to deliver the verification code.
    pub channel: RecoveryChannel,
    /// Credential the caller intends to reset.
    pub purpose: RecoveryPurpose,
}

/// Challenge metadata returned whether or not the account exists.
#[derive(Debug, Serialize, Deserialize)]
pub struct RecoveryChallengeResponse {
    /// Opaque challenge identifier.
    pub challenge_id: Uuid,
    /// Masked destination suitable for display.
    pub destination_hint: String,
    /// Unix timestamp at which the code expires.
    pub expires_at: i64,
}

/// Verifies one recovery code.
#[derive(Debug, Deserialize)]
pub struct RecoveryVerifyRequest {
    /// Opaque challenge identifier from the request step.
    pub challenge_id: Uuid,
    /// Six-digit verification code.
    pub code: String,
}

/// One-time authorization returned after code verification.
#[derive(Debug, Serialize, Deserialize)]
pub struct RecoveryVerifiedResponse {
    /// Opaque single-use token.
    pub recovery_token: String,
    /// Purpose bound to the token.
    pub purpose: RecoveryPurpose,
    /// Unix timestamp at which the token expires.
    pub expires_at: i64,
}

/// Replaces the cloud account password after verification.
#[derive(Debug, Deserialize)]
pub struct RecoveryResetPasswordRequest {
    /// Single-use token bound to account-password recovery.
    pub recovery_token: String,
    /// New cloud account password.
    pub new_password: String,
}

/// Consumes a verified unlock-recovery authorization.
#[derive(Debug, Deserialize)]
pub struct RecoveryAuthorizeUnlockRequest {
    /// Single-use token bound to unlock-password recovery.
    pub recovery_token: String,
}

/// Bearer session returned after authentication.
#[derive(Debug, Serialize, Deserialize)]
pub struct SessionResponse {
    /// Opaque bearer token, returned only at creation.
    pub token: String,
    /// Account identifier.
    pub user_id: Uuid,
    /// Unix timestamp when this session expires.
    pub expires_at: i64,
}

/// Registers a device without giving it decryption capability on the service.
#[derive(Debug, Deserialize)]
pub struct RegisterDeviceRequest {
    /// Client-generated device identifier.
    pub device_id: Uuid,
    /// User-recognizable label.
    pub name: String,
    /// Coarse platform label.
    pub platform: String,
    /// Client-generated high-entropy secret used only to poll and acknowledge
    /// account-owner device-control commands after bearer sessions are revoked.
    ///
    /// Older clients may omit this field, but they cannot receive a durable
    /// remote wipe-and-logout command after revocation.
    #[serde(default)]
    pub control_token: Option<String>,
}

/// Device metadata visible to its account owner.
#[derive(Debug, Serialize, Deserialize)]
pub struct DeviceResponse {
    /// Client-generated stable identifier.
    pub device_id: Uuid,
    /// User-recognizable label.
    pub name: String,
    /// Coarse platform label.
    pub platform: String,
    /// Whether the device has been remotely revoked.
    pub revoked: bool,
    /// Unix timestamp when the device was first registered.
    pub created_at: i64,
    /// Unix timestamp of the most recent authenticated heartbeat.
    pub last_seen_at: i64,
    /// Whether the device has checked in during the current online window.
    pub online: bool,
    /// Whether this device registered a separate control token and can receive
    /// a durable remote wipe-and-logout command after account revocation.
    #[serde(default)]
    pub remote_control_enabled: bool,
}

/// Account-owner command delivered to one client device.
#[derive(Clone, Copy, Debug, Serialize, Deserialize, Eq, PartialEq)]
#[serde(rename_all = "snake_case")]
pub enum DeviceControlAction {
    /// Delete all local HeartLink data protected by the application vault and
    /// end the cloud account session on that device.
    WipeLocalDataAndLogout,
}

/// One durable device-control command.
#[derive(Debug, Serialize, Deserialize)]
pub struct DeviceControlCommand {
    /// Stable command identifier used for idempotent acknowledgement.
    pub command_id: Uuid,
    /// Action the client must complete.
    pub action: DeviceControlAction,
    /// Unix timestamp when the account owner requested the action.
    pub issued_at: i64,
}

/// Device-control poll result.
#[derive(Debug, Serialize, Deserialize)]
pub struct DeviceControlResponse {
    /// Whether the cloud account has revoked this device.
    pub revoked: bool,
    /// Pending command. A delivered command remains present until acknowledged,
    /// so a lost HTTP response cannot lose the wipe instruction.
    pub command: Option<DeviceControlCommand>,
}

/// Idempotently acknowledges a completed device-control command.
#[derive(Debug, Deserialize)]
pub struct AcknowledgeDeviceControlRequest {
    /// Command that the client has completed locally.
    pub command_id: Uuid,
}

/// Pushes exactly one record for clear conflict semantics.
#[derive(Debug, Deserialize)]
pub struct PushRequest {
    /// Opaque encrypted record.
    pub record: CipherRecord,
}

/// Successful push result.
#[derive(Debug, Serialize, Deserialize)]
pub struct PushResponse {
    /// Newly assigned revision.
    pub revision: i64,
}

/// Incremental pull result.
#[derive(Debug, Serialize, Deserialize)]
pub struct PullResponse {
    /// Records after the requested cursor, including tombstones.
    pub records: Vec<RevisionedRecord>,
    /// Highest known revision for the account.
    pub cursor: i64,
}

/// Stable machine-readable error payload.
#[derive(Debug, Serialize, Deserialize)]
pub struct ErrorResponse {
    /// Error category.
    pub code: String,
    /// Safe message suitable for display.
    pub message: String,
}
